### ISSUE TITLE
`global` variable shadowed?

### ISSUE THREAD

**Issue by dosentmatter** [JakeChampion/fetch#1026]
https://github.com/github/fetch/blob/d1d09fb8039b4b8c7f2f5d6c844ea72d8a3cefe6/fetch.js#L1-L5

I'm not sure if I'm reading this wrong, but it seems like the second `global` is shadowed by the `var global` declaration. After hoisting, the equivalent code is

```js
var global; // default undefined
global =
  (typeof globalThis !== 'undefined' && globalThis) ||
  (typeof self !== 'undefined' && self) ||
  (typeof global !== 'undefined' && global) ||
  {}
```

Because of hoisting, the `global` gets evaluated as `false` in all environments:
```js
(typeof global !== 'undefined' && global)
// becomes
(typeof undefined !== 'undefined' && global)
// becomes
('undefined' !== 'undefined' && undefined)
// becomes
(false &&  undefined)
// becomes
false
```

I think the intent was to access the [`global` object](https://developer.mozilla.org/en-US/docs/Glossary/Global_object), if it exists.

We might have to capture it to a variable, `oldGlobal`, first, but the hoisting of `global` prevents us from doing this easily.
For example, the following wouldn't work because `oldGlobal` and `global` declarations are hoisted.
```js
var oldGlobal = global; // === undefined
var global =
  (typeof globalThis !== 'undefined' && globalThis) ||
  (typeof self !== 'undefined' && self) ||
  (typeof oldGlobal !== 'undefined' && oldGlobal) ||
  {}
```

The only solution I can think of that preserves the variable name, `global`, is to wrap the code in an IIFE to prevent hoisting above `oldGlobal`. The `typeof global` is also moved up to `oldGlobal` to prevent errors on environments that don't `global` defined.
```js
var oldGlobal = typeof global !== 'undefined' && global
(function () {
  var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof self !== 'undefined' && self) ||
    oldGlobal ||
    {}

  // rest of the code...
})()
```

An alternative solution is to rename `global` to some other name.

**Comment by dosentmatter** [comment]
Note that the behavior of `var window` or `var global` seems to differ if you are in the global scope or function scope. It also seems to vary depending on the environment and if you are in a file.

Chrome console/snippet:
```js
var window = window;
window; // still the global window
(function () { var window; return window; })(); // undefined
```

Node.js repl:
```js
var global = global;
global; // still the global object
(function () { var global; return global; })(); // undefined
```

Node.js file:
```js
var global = global;
global; // undefined
(function () { var global; return global; })(); // undefined
```

Notice when the code gets wrapped in a function, `window`/`global` is consistently `undefined`. The `fetch` code does get wrapped in a function if we are using a module bundler like `webpack`.

**Comment by Shah8018** [comment]
What happen

**Comment by Gara312** [comment]
> Что происходит

**Comment by Gara312** [comment]
> Обратите внимание, что поведение `var window`или `var global`различаются в зависимости от того, находитесь ли вы в глобальной области, модуле или функции.
> 
> Консоль / фрагмент Chrome: это глобальная область действия и `window`уже объявлена, поэтому `var window`ничего не делает.
> 
> ```js
> var  window  =  window ; 
> окно ;  // по-прежнему глобальное окно 
> ( function  ( )  {  var  window ;  return  window ;  } ) ( ) ;  // неопределенный
> ```
> 
> Ответ Node.js: Также в глобальной области.
> 
> ```js
> var  global  =  global ; 
> глобальный ;  // по-прежнему глобальный объект 
> ( function  ( )  {  var  global ;  return  global ;  } ) ( ) ;  // неопределенный
> ```
> 
> Файл Node.js: область модуля, поэтому `var global`скрывает глобальную область видимости `global`.
> 
> ```js
> var  global  =  global ; 
> глобальный ;  // undefined 
> ( function  ( )  {  var  global ;  return  global ;  } ) ( ) ;  // неопределенный
> ```
> 
> Обратите внимание, когда код оборачивается функцией, `window`/ `global`постоянно `undefined`. `fetch`Код действительно получить завернутые в функцию , если мы используем модуль Bundler как `webpack`.

**Comment by Gara312** [comment]
> https://github.com/github/fetch/blob/d1d09fb8039b4b8c7f2f5d6c844ea72d8a3cefe6/fetch.js#L1-L5
> 
> Я не уверен, что читаю это неправильно, но похоже, что второе `global`затмевается `var global`декларацией. После подъема эквивалентный код будет
> 
> ```js
> var  global ;  // по умолчанию undefined 
> global  = 
>   ( typeof  globalThis  ! ==  'undefined'  &&  globalThis )  || 
>   ( typeof  self  ! ==  'undefined'  &&  self )  || 
>   ( typeof  global  ! ==  'undefined'  &&  global )  || 
>   { }
> ```
> 
> Из-за подъема `global`оценивается как `false`во всех средах:
> 
> ```js
> ( typeof  global  ! ==  'undefined'  &&  global ) 
> // становится 
> ( typeof  undefined  ! ==  'undefined'  &&  global ) 
> // становится 
> ( 'undefined'  ! ==  'undefined'  &&  undefined ) 
> // становится 
> ( false  &&   undefined ) 
> // становится 
> ложным
> ```
> 
> Я думаю, что целью было получить доступ к [`global`объекту](https://developer.mozilla.org/en-US/docs/Glossary/Global_object) , если он существует.
> 
> Возможно `oldGlobal`, нам сначала придется записать его в переменную , но подъем не `global`позволяет нам сделать это легко. Например, следующий не будет работать , потому что `oldGlobal`и `global`декларации водрузили.
> 
> ```js
> var  oldGlobal  =  global ;  // === undefined 
> var  global  = 
>   ( typeof  globalThis  ! ==  'undefined'  &&  globalThis )  || 
>   ( typeof  self  ! ==  'undefined'  &&  self )  || 
>   ( typeof  oldGlobal  ! ==  'undefined'  &&  oldGlobal )  || 
>   { }
> ```
> 
> The only solution I can think of that preserves the variable name, `global`, is to wrap the code in an IIFE to prevent hoisting above `oldGlobal`. The `typeof global` is also moved up to `oldGlobal` to prevent errors on environments that don't `global` defined.
> 
> ```js
> var oldGlobal = typeof global !== 'undefined' && global
> (function () {
>   var global =
>     (typeof globalThis !== 'undefined' && globalThis) ||
>     (typeof self !== 'undefined' && self) ||
>     oldGlobal ||
>     {}
> 
>   // rest of the code...
> })()
> ```
> 
> An alternative solution is to rename `global` to some other name.

**Comment by Gara312** [comment]
> > https://github.com/github/fetch/blob/d1d09fb8039b4b8c7f2f5d6c844ea72d8a3cefe6/fetch.js#L1-L5
> > 
> > Я не уверен, что читаю это неправильно, но похоже, что второе `global`затмевается `var global`декларацией. После подъема эквивалентный код будет
> > ```js
> > var   global  ;   // по умолчанию undefined 
> > global   =  
> >   (  typeof   globalThis   !  ==   'undefined'   &&   globalThis  )   ||  
> >   (  typeof   self   !  ==   'undefined'   &&   self  )   ||  
> >   (  typeof   global   !  ==   'undefined'   &&   global  )   ||  
> >   {  }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Из-за подъема `global`оценивается как `false`во всех средах:
> > ```js
> > (  typeof   global   !  ==   'undefined'   &&   global  )  
> > // становится 
> > (  typeof   undefined   !  ==   'undefined'   &&   global  )  
> > // 
> > (  'undefined'   !  ==   'undefined'   &&   undefined  )  
> > // становится 
> > (  false   &&    undefined  )  
> > // становится 
> > ложным
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Я думаю, что было целью получить доступ к [`global`объекту](https://developer.mozilla.org/en-US/docs/Glossary/Global_object) , если он существует.
> > Возможно `oldGlobal`, нам сначала придется записать его в переменную, но `global`подъем не позволяет нам сделать это легко. Например, следующий не будет работать, потому что `oldGlobal`и `global`декларации водрузили.
> > ```js
> > var   oldGlobal   =   global  ;   // === undefined 
> > var   global   =  
> >   (  typeof   globalThis   !  ==   'undefined'   &&   globalThis  )   ||  
> >   (  typeof   self   !  ==   'undefined'   &&   self  )   ||  
> >   (  typeof   oldGlobal   !  ==   'undefined'   &&   oldGlobal  )   ||  
> >   {  }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Единственное решение, которое я могу придумать, сохраняющее имя переменной `global`, - это обернуть код в IIFE, чтобы предотвратить подъем, указанный выше `oldGlobal`. `typeof global`Также перемещается до , `oldGlobal`чтобы предотвратить ошибки в средах , которые не `global`определены.
> > ```js
> > var  oldGlobal  =  typeof  global  ! ==  'undefined'  &&  global 
> > ( function  ( )  { 
> >   var  global  = 
> >     ( typeof  globalThis  ! ==  'undefined'  &&  globalThis )  || 
> >     ( typeof  self  ! ==  'undefined'  &&  self )  || 
> >     oldGlobal  || 
> >     { }
> > 
> >   // остальной код ... 
> > } ) ( )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Альтернативным решением является переименование `global`на другое имя.

**Comment by Gara312** [comment]
> https://github.com/github/fetch/blob/d1d09fb8039b4b8c7f2f5d6c844ea72d8a3cefe6/fetch.js#L1-L5
> 
> Я не уверен, что читаю это неправильно, но похоже, что второе `global`затмевается `var global`декларацией. После подъема эквивалентный код будет
> 
> ```js
> var  global ;  // по умолчанию undefined 
> global  = 
>   ( typeof  globalThis  ! ==  'undefined'  &&  globalThis )  || 
>   ( typeof  self  ! ==  'undefined'  &&  self )  || 
>   ( typeof  global  ! ==  'undefined'  &&  global )  || 
>   { }
> ```
> 
> Из-за подъема `global`оценивается как `false`во всех средах:
> 
> ```js
> ( typeof  global  ! ==  'undefined'  &&  global ) 
> // становится 
> ( typeof  undefined  ! ==  'undefined'  &&  global ) 
> // становится 
> ( 'undefined'  ! ==  'undefined'  &&  undefined ) 
> // становится 
> ( false  &&   undefined ) 
> // становится 
> ложным
> ```
> 
> Я думаю, что целью было получить доступ к [`global`объекту](https://developer.mozilla.org/en-US/docs/Glossary/Global_object) , если он существует.
> 
> Возможно `oldGlobal`, нам сначала придется записать его в переменную , но подъем не `global`позволяет нам сделать это легко. Например, следующий не будет работать , потому что `oldGlobal`и `global`декларации водрузили.
> 
> ```js
> var  oldGlobal  =  global ;  // === undefined 
> var  global  = 
>   ( typeof  globalThis  ! ==  'undefined'  &&  globalThis )  || 
>   ( typeof  self  ! ==  'undefined'  &&  self )  || 
>   ( typeof  oldGlobal  ! ==  'undefined'  &&  oldGlobal )  || 
>   { }
> ```
> 
> Единственное решение, которое я могу придумать, сохраняющее имя переменной `global`, - это обернуть код в IIFE, чтобы предотвратить подъем, указанный выше `oldGlobal`. `typeof global`Также перемещается до , `oldGlobal`чтобы предотвратить ошибки в средах , которые не `global`определены.
> 
> ```js
> var  oldGlobal  =  typeof  global  ! ==  'undefined'  &&  global 
> ( function  ( )  { 
>   var  global  = 
>     ( typeof  globalThis  ! ==  'undefined'  &&  globalThis )  || 
>     ( typeof  self  ! ==  'undefined'  &&  self )  || 
>     oldGlobal  || 
>     { }
> 
>   // остальной код ... 
> } ) ( )
> ```
> 
> Альтернативным решением является переименование `global`на другое имя.

**Comment by oliverlj** [comment]
I'm wondering if this is causing error I have.
```
 Failed to execute 'fetch' on 'Window': Failed to read the 'signal' property from 'RequestInit': Failed to convert value to 'AbortSignal'.
```

i saw this other doing an import : https://github.com/Azure/azure-sdk-for-js/pull/9880
