### ISSUE TITLE
readBlobAsText does not repect the reponse charset

### ISSUE THREAD

**Issue by joe06102** [JakeChampion/fetch#1059]
I'm working on a **react-native** project which is dependent of this lib. But I found the `readBlobAsText` does not respect the `charset` in `Content-Type`, which throws error when the charset is not utf8-encoded.

the problematic code below:

```javascript
function readBlobAsText(blob) {
  var reader = new FileReader()
  var promise = fileReaderReady(reader)
  reader.readAsText(blob) // <-- FilerReader accept a second param 'encode', which can be retrieved from the response header.
  return promise
}
```

And here is my code suggestion:

```javascript
  function getEncode() {
    const contentType = xhr.getResponseHeader('content-type')
    return /charset=([A-Za-z0-9_\-]+)/.exec(contentType)?.[1] || 'utf-8'
  }
```

**Comment by joe06102** [comment]
is this repo dead?

**Comment by Gara312** [comment]
> Я работаю над **реактивным** проектом, который зависит от этой библиотеки. Но я обнаружил, что `readBlobAsText`не соблюдается `charset`in `Content-Type`, что вызывает ошибку, если кодировка не кодируется в utf8.
> 
> проблемный код ниже:
> 
> ```js
> Функция  readBlobAsText ( клякса )  { 
>   вар  читатель  =  новый  FileReader ( ) 
>   вар  обещание  =  fileReaderReady ( читатель ) 
>   читатель . readAsText ( blob )  // <- FilerReader принимает второй параметр 'encode', который можно получить из заголовка ответа. 
>   вернуть  обещание 
> }
> ```
> 
> И вот мое предложение кода:
> 
> ```js
>   функция  getEncode ( )  { 
>     const  contentType  =  xhr . getResponseHeader ( 'content-type' ) 
>     return  / charset = ( [ A-Za-z0-9_ \ - ] + ) / . exec ( contentType ) ?. [ 1 ]  ||  'utf-8' 
>   }
> ```

**Comment by Gara312** [comment]
> Привет, нет, все еще поддерживается

**Comment by Gara312** [comment]
> это репо мертво?

**Comment by Gara312** [comment]
Duplicate of #

**Comment by Gara312** [comment]
> Я работаю над **реактивным** проектом, который зависит от этой библиотеки. Но я обнаружил, что `readBlobAsText`не соблюдается `charset`in `Content-Type`, что вызывает ошибку, если кодировка не кодируется в utf8.
> 
> проблемный код ниже:
> 
> ```js
> Функция  readBlobAsText ( клякса )  { 
>   вар  читатель  =  новый  FileReader ( ) 
>   вар  обещание  =  fileReaderReady ( читатель ) 
>   читатель . readAsText ( blob )  // <- FilerReader принимает второй параметр 'encode', который можно получить из заголовка ответа. 
>   вернуть  обещание 
> }
> ```
> 
> И вот мое предложение кода:
> 
> ```js
>   функция  getEncode ( )  { 
>     const  contentType  =  xhr . getResponseHeader ( 'content-type' ) 
>     return  / charset = ( [ A-Za-z0-9_ \ - ] + ) / . exec ( contentType ) ?. [ 1 ]  ||  'utf-8' 
>   }
> ```

**Comment by Gara312** [comment]
> это репо мертво?
