### ISSUE TITLE
Fix Request.formdata() method

### ISSUE THREAD

**Issue by Khartir** [JakeChampion/fetch#1149]
The `formdata()`-method should return  a `FormData` object of the request (https://developer.mozilla.org/en-US/docs/Web/API/Request/formData). However as far as I can see, the implementation of the method [relies on the `text()` method ](https://github.com/github/fetch/blob/fb5b0cf42b470faf8c5448ab461d561f34380a30/fetch.js#L320)which [explicitly does not work](https://github.com/github/fetch/blob/fb5b0cf42b470faf8c5448ab461d561f34380a30/fetch.js) with `FormData`.

**Comment by JakeChampion** [comment]
`formData` does return a `FormData` instance however we don't provide a `FormData` polyfill, you will need to supply one yourself
