### ISSUE TITLE
This repository is moving from the github org

### ISSUE THREAD

**Issue by zkoppert** [JakeChampion/fetch#1349]
# This repository is moving!!!
## Why?

In a bid to improve security of GitHub's primary organisation https://github.com/github, GitHub is moving all repositories with outside collaborators out of the organisation. This repository is one of those.

## When?

There is no specific date, but it will be before the end of July 2023.

## What will happen?

The repository will be moved to the new organisation at https://github.com/JakeChampion/fetch (there's nothing there right now).

All current external contributors will retain their access.

Old external contributors will lose their access, if they haven't already.

All PRs should automatically rebase to the new repository location so you shouldn't need to do anything. If they don't please open an issue and I'll try sort things out.

All issues and discussions will be moved across at the same time too.

**Comment by andreymal** [comment]
The link [github.github.io/fetch/](https://github.github.io/fetch/) in README.md and "About" is broken now
