### ISSUE TITLE
Create a Security Policy

### ISSUE THREAD

**Issue by joycebrum** [JakeChampion/fetch#1373]
Hi, I've noticed that the security policy got lost in this recent changing in the repo. I believe it was using the github standard security policy before https://github.com/github/.github/blob/main/SECURITY.md.

Since this is an important document to ensure a safe and timely vulnerability report process, I'd like to suggest to define one for jakechampion/fetch repository. 

There are a few ways to receive such disclosures:
- have an email or website available to receive such reports (such as opensource-security[@]github.com); and/or
- use [GitHub's private vulnerability reporting](https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository) feature.

Let me know if a PR suggesting a Security Policy is welcome and I'll submit it ASAP.

**Comment by JakeChampion** [comment]
@joycebrum I'd be happy to accept a PR for such a document 👍
