### ISSUE TITLE
Enable OpenSSF Scorecard Action 

### ISSUE THREAD

**Issue by joycebrum** [JakeChampion/fetch#1379]
Hi again, I'd like to suggest the adoption of the [OpenSSF Scorecard Action](https://github.com/ossf/scorecard-action). It is a tool developed by the Open Source Security Foundation that analyse the project looking for possible improvements regarding supply-chain security practices.

It generates warnings with the findings that (optionally) can be seen in the [security dashboard](https://github.com/JakeChampion/fetch/security). The project's score can also be optionally shared through a badge.
![image](https://github.com/JakeChampion/fetch/assets/22223372/51aad60f-666c-493f-a4a7-19123485d40b)

Let me know if you are interesting on the tool and I can submit a PR configuring it.

Thanks!

**Comment by JakeChampion** [comment]
@joycebrum I'm happy to try out this tool, if you supply a PR configuring it that'd be great 🙇

**Comment by Mertz22** [comment]
How does this tool work can you put me through it

**Comment by joycebrum** [comment]
Sure! It uses the [GitHub APIs](https://docs.github.com/pt/rest?apiVersion=2022-11-28) and [GraphQL](https://docs.github.com/en/graphql) to gather information about the project and understand possible improvements considering a [set of criteria](https://github.com/ossf/scorecard#scorecard-checks). 

These criteria are ways to mitigate known supply-chain attack vectors. 

The tool is an Open Source Security Foundation initiative to fight the increasing on supply-chain attack incidents.
