### ISSUE TITLE
code is working in chrome, not in firefox

### ISSUE THREAD

**Issue by schoormans** [JakeChampion/fetch#1389]
the data that is put in the html form, is send through a php file to store in a json file. when the user, has paid, they are send to a php file the php file takes the data out of the json file and uses it. it is working great in chrome. but in firefox the data is not being send.
 here is my html form and the
`<form action="https://buy.stripe.com/9AQ9CI4Sy8JoaxG4gj" id="PhpGegevens" class="mouseover" > 
                          
</br>
</br>

<label>Naam:</label><input name="Naam" type="text" class="input"  /><br>
<label>Datum:</label><input name="Datum" type="text" class="input"  /><br>
<label>Email:</label><input name="Email" type="text" class="input"  /><br>

<script type="text/javascript">
function showIt(imgsrc)
{
document.getElementById('imageshow').src=imgsrc;
}

function hideIt()
{
document.getElementById('imageshow').src="images1/lege paspop W2.jpeg";
}
</script>

<span onmouseover="showIt('images1/taillewijdte712.jpeg')" onmouseout="hideIt()"><label>Taillewijdte (in mm):</label><input name="TailleWijdte" type="text" class="input" /></span><br>
<span onmouseover="showIt('images1/poppop heupwijdte.jpeg')" onmouseout="hideIt()"><label>Heupwijdte (in mm):</label><input name="HeupWijdte" type="text" class="input" /></span><br>
<span onmouseover="showIt('images1/heuphoogte paspop W2.jpeg')" onmouseout="hideIt()"><label>Heuphoogte (in mm):</label><input name="HeupHoogte" type="text" class="input" /></span><br>
<span onmouseover="showIt('images1/bovenwijdte.jpeg')" onmouseout="hideIt()"><label>Bovenwijdte (in mm):</label><input name="BovenWijdte" type="text" class="input" /></span><br>
<span onmouseover="showIt('images1/lichaamslengte (1).jpeg')" onmouseout="hideIt()"><label>Lichaamslengte (in mm):</label><input name="LichaamsLengte" type="text" class="input" /></span><br>
<span onmouseover="showIt('images1/bustediepte.jpeg')" onmouseout="hideIt()"><label>Bustediepte (in mm):</label><input name="BusteDiepte" type="text" class="input" /></span><br>

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<br> 
<input type="submit" id="bt" value="Verzenden" onclick="saveFile()" />
<script> 

function saveFile() {
    // Collect form data
    
    const naam = document.querySelector('input[name="Naam"]').value;
    const datum = document.querySelector('input[name="Datum"]').value;
    const email = document.querySelector('input[name="Email"]').value;
    const tailleWijdte = document.querySelector('input[name="TailleWijdte"]').value;
    const heupWijdte = document.querySelector('input[name="HeupWijdte"]').value;
    const heupHoogte = document.querySelector('input[name="HeupHoogte"]').value;
    const bovenWijdte = document.querySelector('input[name="BovenWijdte"]').value;
    const lichaamsLengte = document.querySelector('input[name="LichaamsLengte"]').value;
    const busteDiepte = document.querySelector('input[name="BusteDiepte"]').value;
    

    // Create a JavaScript object to hold the form data
    const formData = {
        Naam: naam,
        Datum: datum,
        Email: email,
        TailleWijdte: tailleWijdte,
        HeupWijdte: heupWijdte,
        HeupHoogte: heupHoogte,
        BovenWijdte: bovenWijdte,
        LichaamsLengte: lichaamsLengte,
        BusteDiepte: busteDiepte,
        
        
    };

    // Send the data to the server as JSON
    fetch("zzsave_data13shirt.php", {
        method: "POST",
        body: JSON.stringify(formData),
        headers: {
            "Content-Type": "application/json",
        },
        mode: "cors", // Add this line
    })
    .then((response) => {
        if (response.ok) {
            // Successful response, you can handle it here
            console.log("Data saved successfully");
        } else {
            // Handle errors here
            console.error("Error:", response.status, response.statusText);
        }
    })
    .catch((error) => {
    console.error("Error occurred during fetch:", error);
    // Log the error details for further debugging
   
});

}
</script>`

**Comment by schoormans** [comment]
this is my webpage
https://patternsbyanoukschoormans.com/z123shirt.html

**Comment by JakeChampion** [comment]
This doesn't look like an issue related to this fetch polyfill to me
