### ISSUE TITLE
suggestion to use str.indexOf(searchString) === 0 for better compatibility

### ISSUE THREAD

**Issue by elasim** [JakeChampion/fetch#1403]
According to caniuse, the browser coverage for the fetch API is similar to the support range for String.prototype.startsWith,
which suggests that browsers requiring a fetch polyfill would likely also need a polyfill for the startsWith API.

Therefore, it would be advisable to use str.indexOf(searchString) === 0 instead of startsWith in the code for better compatibility across browsers

<img width="1398" alt="image" src="https://github.com/JakeChampion/fetch/assets/1837682/35662b80-2822-4fcc-9360-a468a3fcb848">

https://github.com/JakeChampion/fetch/blob/b5cee5093bb4929239b74b9394e51355b231c460/fetch.js#L544-L550

**Comment by JakeChampion** [comment]
I'll happily accept a pull request if you are up for submitting one

**Comment by vamshisuram** [comment]
@elasim Good point 👍
