### ISSUE TITLE
UMD Releases don't exist

### ISSUE THREAD

**Issue by polarina** [JakeChampion/fetch#1405]
The README states:
> As an alternative to using npm, you can obtain fetch.umd.js from the [Releases](https://github.com/github/fetch/releases) section. The UMD distribution is compatible with AMD and CommonJS module loaders, as well as loading directly into a page via <script> tag.

The release section does not contain any `fetch.umd.js` files.

**Comment by JakeChampion** [comment]
thanks for the issue, we no longer make umd releases, i've now removed this from the readme
