### ISSUE TITLE
The value can contains newlines as value

### ISSUE THREAD

**Issue by yhojann-cl** [JakeChampion/fetch#841]
In the https://github.com/github/fetch/blob/master/fetch.js#L58 the value can contains newlines as value, you can execute a header injection, by example, to inject cookies or custom authentication from dynamics values.

In the real function on a web browser, the values are restricted:

```javascript
new Headers({'Accept': 'foo\nCookie:abc'})
Uncaught TypeError: Headers constructor: foo
Cookie:abc is an invalid header value.
    <anonymous> debugger eval code:1
```

And in https://github.com/github/fetch/blob/master/fetch.js#L571 the fetch function set the custom headers in raw mode to XHR, the values is not validated, by example: You can made own custom `FakeHeaders` class and set a invalid values, like as newlines, use the original `Headers` class is not necessary.

When send a custom `FakeHeades` to a `headers` argument of fetch in web browser, says:

```javascript
fetch('http://example.com/', {
    method: 'POST',
    mode: 'no-cors',
    credentials: 'omit',
    headers: new FakeHeaders({ 'Accept': 'foo\nCookie: abc' }),
    body: '<abc />'
})
.then(function(data){ console.log(data) });
Uncaught (in promise) TypeError: Window.fetch: function(name){
        return this.has(name) ? this.map[name] : null;
    } is an invalid header value.
    <anonymous> debugger eval code:1
```

And... you can write the `Cookie` and `Authorization` header value? in the web browser it is not possible for security reasons.

**Comment by ashokirla** [comment]
test comment

**Comment by ashokirla** [comment]
test comment.

**Comment by ashokirla** [comment]
asdfadsf

**Comment by KVROHITH098** [comment]
ok so what was the cookie about?

**Comment by Shah8018** [comment]
Yo maanage all your path 
To get easy
how ever or when use the app. Open NJow

**Comment by Gara312** [comment]
> Yo управляйте всем своим путем, чтобы упростить использование приложения, как бы то ни было и когда. Открыть NJow

**Comment by Gara312** [comment]
> > Yo управляйте всем своим путем, чтобы упростить использование приложения. Открыть NJow

**Comment by JakeChampion** [comment]
>And... you can write the Cookie and Authorization header value? in the web browser it is not possible for security reasons.

This polyfill works in more places than browsers, which is why we need to support Cooke and Authorization
