### ISSUE TITLE
blob.text is not a function

### ISSUE THREAD

**Issue by imtaotao** [JakeChampion/fetch#861]
Is this a bug ?

```js
fetch(url, conf)
   .then((res) => res.blob())
   .then((blob) => {
      return blob.text().then((code) => {

    })
  }
```

**Comment by yendi158** [comment]
#861

**Comment by YJ8CJY3MRGJ7MLLT9H3Q** [comment]
في الاثنين، ١٦ نوفمبر ٢٠٢٠ ١١:٥٨ ص Arthur <notifications@github.com> كتب:

**Comment by 0531283028** [comment]
> [https://github.com/github/fetch/issues/861#issuecomment-728979430]()

**Comment by HACK3909** [comment]
[ in

**Comment by danielimmke** [comment]
This is still an issue

**Comment by aryan29** [comment]
still an issue

**Comment by wtLau** [comment]
still any issue

**Comment by ZukaiGong** [comment]
I triggered this bug today and I don't know why.

**Comment by JakeChampion** [comment]
This project does not provide a polyfill for `blob`
