### ISSUE TITLE
Use of Content-Type (vs Accept) header for setting XHR responseType to 'arraybuffer'

### ISSUE THREAD

**Issue by sfuqua** [JakeChampion/fetch#997]
When fetching, we have this block to configure the outbound XHR:

```js
    if ('responseType' in xhr) {
      if (support.blob) {
        xhr.responseType = 'blob'
      } else if (
        support.arrayBuffer &&
        request.headers.get('Content-Type') &&
        request.headers.get('Content-Type').indexOf('application/octet-stream') !== -1
      ) {
        xhr.responseType = 'arraybuffer'
      }
    }
```

I'm curious why the request's `Content-Type` is used as a heuristic for requesting an ArrayBuffer. For a GET request, we often won't have a `Content-Type` at all because there's no body in the request.

Should this instead be the Accept header, indicating the type of content that the sender is expecting to receive from the server?

My team is running into an issue where in order to get the desired behavior from the polyfill we need to add a `Content-Type` header to our requests which is a bit unnatural - it seems like `Accept` is a cleaner HTTP fit here.

This issue is exposed on React Native clients where ArrayBuffer works as expected (so we want an ArrayBuffer out of the XHR), but Blob does not, so `support.blob` is false.

**Comment by gguyza001** [comment]
VOCA Fix to Sustain the Crime Victims Fund Act of 2021
This bill adds a new source of revenue for the Crime Victims Fund and makes changes to formula grants supported by the fund.
Specifically, the bill directs revenues collected from deferred prosecution and non-prosecution agreements to be deposited into the Crime Victims Fund. Currently, such revenues are deposited into the general fund of the Treasury.
Additionally, the bill increases the percentage—from 60% to 75%—of state compensation payments to crime victims in the prior fiscal year used to calculate formula grants for state victim compensation programs.
Finally, the bill directs states to waive the matching requirement for recipients of state victim assistance formula grants during and for one year after a pandemic-related national emergency. It also allows states to waive the matching requirement pursuant to a policy established by the state.

**Comment by MintThitiratChamnan** [comment]
> When fetching, we have this block to configure the outbound XHR:
> 
> ```js
>     if ('responseType' in xhr) {
>       if (support.blob) {
>         xhr.responseType = 'blob'
>       } else if (
>         support.arrayBuffer &&
>         request.headers.get('Content-Type') &&
>         request.headers.get('Content-Type').indexOf('application/octet-stream') !== -1
>       ) {
>         xhr.responseType = 'arraybuffer'
>       }
>     }
> ```
> 
> I'm curious why the request's `Content-Type` is used as a heuristic for requesting an ArrayBuffer. For a GET request, we often won't have a `Content-Type` at all because there's no body in the request.
> 
> Should this instead be the Accept header, indicating the type of content that the sender is expecting to receive from the server?
> 
> My team is running into an issue where in order to get the desired behavior from the polyfill we need to add a `Content-Type` header to our requests which is a bit unnatural - it seems like `Accept` is a cleaner HTTP fit here.
> 
> This issue is exposed on React Native clients where ArrayBuffer works as expected (so we want an ArrayBuffer out of the XHR), but Blob does not, so `support.blob` is false.

https://github.com/github/fetch/issues/997#issue-950012817

**Comment by hanhphucbuon996** [comment]
> When fetching, we have this block to configure the outbound XHR:
> 
> ```js
>     if ('responseType' in xhr) {
>       if (support.blob) {
>         xhr.responseType = 'blob'
>       } else if (
>         support.arrayBuffer &&
>         request.headers.get('Content-Type') &&
>         request.headers.get('Content-Type').indexOf('application/octet-stream') !== -1
>       ) {
>         xhr.responseType = 'arraybuffer'
>       }
>     }
> ```
> 
> I'm curious why the request's `Content-Type` is used as a heuristic for requesting an ArrayBuffer. For a GET request, we often won't have a `Content-Type` at all because there's no body in the request.
> 
> Should this instead be the Accept header, indicating the type of content that the sender is expecting to receive from the server?
> 
> My team is running into an issue where in order to get the desired behavior from the polyfill we need to add a `Content-Type` header to our requests which is a bit unnatural - it seems like `Accept` is a cleaner HTTP fit here.
> 
> This issue is exposed on React Native clients where ArrayBuffer works as expected (so we want an ArrayBuffer out of the XHR), but Blob does not, so `support.blob` is false.

**Comment by mohsin1980** [comment]
> #1366

**Comment by mohsin1980** [comment]
#928
